name: Build Android

on:
  push:
    branches:
      - master

jobs:
  apk:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.0
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Node Packages & add cap/android
        run: npm i && npx cap add android
      - name: Build App
        run: npm run dev:build && npm run cap-sync:android
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: build the APK
        run: cd android && bash gradlew assembleDebug --stacktrace
      - name: Upload to FileIO
        run: curl -F file=@android/app/build/outputs/apk/debug/app-debug.apk file.io
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
